a <- list(id=1,title="great idea",abstract="First,\n;Second:\nand then do it.")
a
write.csv(a,file = "a.csv")
write.csv(a,file = "a.csv",row.names = F)
aaa <- list(a,a,a)
b <- do.call("rbind",aaa)
as_tibble(b)
as_tibble(data.frame(b))
a_safe <- lapply(a, function(x)gsub("\\s"," ",x))
aaa_safe <- lapply(aaa,function(a)lapply(a,function(x)gsub("\\s"," ",x)))
